name: Colors

on: push

jobs:
  colors-debug:
    name: Colorssss
    runs-on: ubuntu-latest
    steps:
      - name: test colors
        shell: bash
        run: |
            python3 -c '
            warn = "\033[93m"
            err = "\033[91m"
            end = "\033[0m"
            print(warn + "WARN" + end + ": some error message")
            print(err + "ERROR" + end + ": some error message")
            '
